all:
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: ansible.netcommon.network_cli
    ansible_user: admin
    ansible_password: "{{ vault_ssh_password }}"
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: "{{ vault_enable_password }}"
    ansible_ssh_common_args: >-
      -o KexAlgorithms=+diffie-hellman-group14-sha1
      -o HostKeyAlgorithms=+ssh-rsa
      -o PubkeyAcceptedAlgorithms=+ssh-rsa
  children:
    routers:
      hosts:
        r-edge:
          ansible_host: 10.10.254.1
    switches:
      children:
        core_switches:
          hosts:
            sw-core:
              ansible_host: 10.10.99.1
        access_switches:
          hosts:
            sw-acc1:
              ansible_host: 10.10.99.11
            sw-acc2:
              ansible_host: 10.10.99.12