---
- name: Deploy switch configurations
  hosts: switches
  tasks:
    - name: DEBUG check vlans before roles
      ansible.builtin.debug:
        var: vlans
  roles:
    - vlan
    - routing
    - dhcp
    - acl

- name: Deploy router configurations
  hosts: routers
  roles:
    - routing
    - nat

- name: Save configurations
  hosts: all
  tasks:
    - name: Save running-config to startup-config
      cisco.ios.ios_config:
        save_when: modified
